name: ts compile

on:
  push:
    branches: 
      - master

jobs:
  compile:
    name: compilets
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: ['8', '10', '12']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
